pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                cd CC_LAB-6
                docker build -t backend-app backend
                '''
            }
        }

        stage('Remove Old Containers') {
            steps {
                sh '''
                docker rm -f backend1 backend2 nginx || true
                '''
            }
        }

        stage('Run Backend Containers') {
            steps {
                sh '''
                docker run -d --name backend1 backend-app
                docker run -d --name backend2 backend-app
                '''
            }
        }

        stage('Run Nginx Load Balancer') {
            steps {
                sh '''
                docker run -d \
                --name nginx \
                -p 8081:80 \
                nginx
                '''
            }
        }
    }
}
